# Available fonts without any further configuration are: Arial Courier, Helvetica and Times
# Check the README.md to see how to add and use more fonts.

# fontBody:
# fontBodyBold:
fontTitle: Helvetica
# fontDescriptorFile:

dateFormat: 02/01/2006

textTitle: INVOICE
textTableColumns:
  - Description
  - Quantity
  - Price
  - Line Total
textDate1: Issue date
textDate2: Due date
textFooterTitle: Payment details
